// <auto-generated />
using Labb_LINQ.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labb_LINQ.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    [Migration("20240411092023_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Labb_LINQ.Models.Course", b =>
                {
                    b.Property<int>("CourseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseID"), 1L, 1);

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseID");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseID = 1,
                            CourseName = "SUT23"
                        },
                        new
                        {
                            CourseID = 2,
                            CourseName = "SUT24"
                        });
                });

            modelBuilder.Entity("Labb_LINQ.Models.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentID"), 1L, 1);

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeacherID")
                        .HasColumnType("int");

                    b.HasKey("StudentID");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentID = 1,
                            StudentName = "Anton Larsson",
                            TeacherID = 1
                        },
                        new
                        {
                            StudentID = 2,
                            StudentName = "Anton Larsson",
                            TeacherID = 2
                        },
                        new
                        {
                            StudentID = 3,
                            StudentName = "Anton Larsson",
                            TeacherID = 4
                        },
                        new
                        {
                            StudentID = 4,
                            StudentName = "Anton Larsson",
                            TeacherID = 3
                        },
                        new
                        {
                            StudentID = 5,
                            StudentName = "Anton Larsson",
                            TeacherID = 1
                        });
                });

            modelBuilder.Entity("Labb_LINQ.Models.Subject", b =>
                {
                    b.Property<int>("SubjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectID"), 1L, 1);

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubjectID");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            SubjectID = 1,
                            SubjectName = "Advanced.NET"
                        },
                        new
                        {
                            SubjectID = 2,
                            SubjectName = "Programing 1"
                        },
                        new
                        {
                            SubjectID = 3,
                            SubjectName = "Math"
                        },
                        new
                        {
                            SubjectID = 4,
                            SubjectName = "Programing 2"
                        });
                });

            modelBuilder.Entity("Labb_LINQ.Models.Teacher", b =>
                {
                    b.Property<int>("TeacherID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherID"), 1L, 1);

                    b.Property<int>("SubjectID")
                        .HasColumnType("int");

                    b.Property<string>("TeacherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeacherID");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            TeacherID = 1,
                            SubjectID = 1,
                            TeacherName = "Anas Qlok"
                        },
                        new
                        {
                            TeacherID = 2,
                            SubjectID = 2,
                            TeacherName = "Tobias Qlok"
                        },
                        new
                        {
                            TeacherID = 3,
                            SubjectID = 3,
                            TeacherName = "Reidar Qlok"
                        },
                        new
                        {
                            TeacherID = 4,
                            SubjectID = 1,
                            TeacherName = "Sara Sarasson"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
